CREATE TABLE IF NOT EXISTS `cp_clientes_potenciales` (
  `id_cliente_potencial` bigint(20) NOT NULL AUTO_INCREMENT,
  `uuid_cliente_potencial` binary(16) NOT NULL,
  `nombre` varchar(255) DEFAULT NULL,
  `apellido` varchar(100) DEFAULT NULL,
  `apellido_materno` varchar(100) DEFAULT NULL,
  `apellido_casada` varchar(100) DEFAULT NULL,
  `compania` varchar(200) DEFAULT NULL,
  `telefono` varchar(100) DEFAULT NULL,
  `correo` varchar(200) DEFAULT NULL,
  `id_cargo` int(11) DEFAULT NULL,
  `id_toma_contacto` int(11) DEFAULT NULL,
  `descripcion_toma_contacto` text,
  `referido_por` varchar(200) DEFAULT NULL,
  `comentarios` text,
  `fecha_creacion` datetime DEFAULT NULL,
  `creado_por` int(11) DEFAULT NULL COMMENT 'id_usuario',
  PRIMARY KEY (`uuid_cliente_potencial`),
  KEY `id_cliente_potencial` (`id_cliente_potencial`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;